// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi7LzqRcPUQhl_cKpcYhtRp89JuoHj4kA',
    appId: '1:207439129688:web:69cef54c992a6b4b80ae2d',
    messagingSenderId: '207439129688',
    projectId: 'farm2screen',
    authDomain: 'farm2screen.firebaseapp.com',
    storageBucket: 'farm2screen.firebasestorage.app',
    measurementId: 'G-LZG9S6BXJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvVr3XG36S3e1z_bTm_FF6OWSOVX9f5K4',
    appId: '1:207439129688:android:91e862417550996380ae2d',
    messagingSenderId: '207439129688',
    projectId: 'farm2screen',
    storageBucket: 'farm2screen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKz5mznjdhMkoG46b3aqGBV-O6gdBk76E',
    appId: '1:207439129688:ios:11664c8d12b795f380ae2d',
    messagingSenderId: '207439129688',
    projectId: 'farm2screen',
    storageBucket: 'farm2screen.firebasestorage.app',
    iosBundleId: 'com.example.farm2screen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKz5mznjdhMkoG46b3aqGBV-O6gdBk76E',
    appId: '1:207439129688:ios:11664c8d12b795f380ae2d',
    messagingSenderId: '207439129688',
    projectId: 'farm2screen',
    storageBucket: 'farm2screen.firebasestorage.app',
    iosBundleId: 'com.example.farm2screen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi7LzqRcPUQhl_cKpcYhtRp89JuoHj4kA',
    appId: '1:207439129688:web:9450215b98bee16880ae2d',
    messagingSenderId: '207439129688',
    projectId: 'farm2screen',
    authDomain: 'farm2screen.firebaseapp.com',
    storageBucket: 'farm2screen.firebasestorage.app',
    measurementId: 'G-Y2YHL4CC6L',
  );
}
